### ISSUE TITLE
webdriver quits right after executed, if driver is installed with this module

### ISSUE THREAD

**Issue by anawkward** [yeongbin-jo/python-chromedriver-autoinstaller#12]
With codes below,

`chromepath = chromedriver_autoinstaller.install(cwd=True)`
`webdriver.Chrome(chromepath,options = options, service_log_path="C:/Users/stat113-00/Desktop/log.log")`

a chormesession quickly closed right after it appeared. according to chromedriver log,
It seems some process executed from this module is not deleted completely, affecting an executed webdriver even after the installation.

with this "https://stackoverflow.com/questions/59416829/any-way-to-leave-selenium-web-pages-open-after-running-your-script-completely-in" reference, adding an experimental options with this

`options.add_experimental_option("detach", True)`

line of code, the problem is monkey patched.

Hope this debugging case can be a help for making further updates

**Comment by yeongbin-jo** [comment]
Thanks for the report.
But, this error cannot be reproduced.
More information is needed.
