### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'

### ISSUE THREAD

**Issue by jalovisko** [yeongbin-jo/python-chromedriver-autoinstaller#16]
I have an issue similar to #1 but on Manjaro and with google-chrome. When invoking `chromedriver_autoinstaller.install()` I receive
```
(base) [jalovisko@jalovisko-manjaro ringuo]$ python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jalovisko/dev/ringuo/venv/lib/python3.9/site-packages/chromedriver_autoinstaller/__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "/home/jalovisko/dev/ringuo/venv/lib/python3.9/site-packages/chromedriver_autoinstaller/utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "/home/jalovisko/dev/ringuo/venv/lib/python3.9/site-packages/chromedriver_autoinstaller/utils.py", line 107, in get_chrome_version
    with subprocess.Popen([executable_name, '--version'], stdout=subprocess.PIPE) as proc:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'
```

**Comment by navdeepgaur** [comment]
do you have google chrome installed? Are you able to run it with `google-chrome` from terminal?

**Comment by jalovisko** [comment]
@navdeepgaur, yes, Google Chrome is installed, though it is ran via `google-chrome-stable`. It was installed from [AUR](https://aur.archlinux.org/packages/google-chrome/). I also have the driver installed from [AUR](https://aur.archlinux.org/packages/chromedriver/).
```
$ which google-chrome-stable
/usr/bin/google-chrome-stable
$ which chromedriver
/usr/bin/chromedriver
```

**Comment by navdeepgaur** [comment]
Could you try the solution here and see if it works for you?

https://stackoverflow.com/a/46275911/2879215

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions

chromedriver = "/path/to/chromedriver"
options = Options()
options.binary_location = '/path/to/chrome'
driver = webdriver.Chrome(chromedriver, chrome_options=options)
```

**Comment by jalovisko** [comment]
Yes, that way it works. But there is no autoinstallation of the Chrome Driver happening, it is manual this way.

**Comment by navdeepgaur** [comment]
If you see that the issue is, installer looks for google-chrome which in your system is available only as google-chrome-stable, could you just create an alias for it in your .bashrc?
https://www.tecmint.com/create-alias-in-linux/

run in terminal or add in in .bashrc
```bash
alias google-chrome=google-chrome-stable
```
if that doesn't work, you can try creating an executable link to `google-chrome-stable` with name `google-chrome`
```bash
sudo ln -s /usr/bin/google-chrome-stable /usr/bin/google-chrome
sudo chmod +x /usr/bin/google-chrome
```

**Comment by jalovisko** [comment]
This is a great solution, thank you @navdeepgaur, it works!
