### ISSUE TITLE
not adding driver to path on Mac

### ISSUE THREAD

**Issue by leao-nardo** [yeongbin-jo/python-chromedriver-autoinstaller#17]
i just read that and user had this problem there

"I did have to make an additional change to my code, which was that I was specifying the path of the driver explicitly [as in driver = webdriver.Chrome(executable_path=CHROMEDRIVER_PATH,options=chrome_options) ], but had to remove the explicit mention for it to work. "

https://stackoverflow.com/questions/50692358/how-to-work-with-a-specific-version-of-chromedriver-while-chrome-browser-gets-up/63985206#63985206

**Comment by navdeepgaur** [comment]
I think there is a solution on the stackoverflow link you posted.
