### ISSUE TITLE
behind proxy

### ISSUE THREAD

**Issue by marekmichalik** [yeongbin-jo/python-chromedriver-autoinstaller#18]
Big thanks for this!
Is there a way to specify proxy for chromedriver download?

**Comment by navdeepgaur** [comment]
set http_proxy and https_proxy environment variables.

for example on windows if your , run this:
set https_proxy=http://username:password@proxy.example.com
set http_proxy=http://username:password@proxy.example.com

or 
setx https_proxy=http://username:password@proxy.example.com
setx http_proxy=http://username:password@proxy.example.com

if you want to permanently create these environment variables in your profile.

**Comment by navdeepgaur** [comment]
Hi @yeongbin-jo, I think this issue is also handled outside the lib and can be closed from here, again, thanks for the nice work on the lib!
