### ISSUE TITLE
<urlopen error [Errno 2] No such file or directory> - Proxy issue

### ISSUE THREAD

**Issue by koroner1** [yeongbin-jo/python-chromedriver-autoinstaller#22]
Hello,
Could you give option to use proxy and replace:
`doc = urllib.request.urlopen('https://chromedriver.storage.googleapis.com').read()`

to:
`http = urllib3.proxy_from_url(proxy)`
`doc = http.request('GET', 'https://chromedriver.storage.googleapis.com').data`

I can't set [http_proxy] environment variables from [this Issue](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/issues/18), because:
`ERROR: Access to the registry path is denied`

**Comment by yeongbin-jo** [comment]
Thanks for your comments.

First, I will review whether it can be solved with a monkey patch, and then will reply to you later.

**Comment by yeongbin-jo** [comment]
As of version `0.4.0`, the option no_ssl has been added to download chromedriver using **only `http` without using ssl**.
I hope this option will solve your problem.
