### ISSUE TITLE
Does not seem to work with Brave browser - Version 1.27.109 Chromium: 92.0.4515.115

### ISSUE THREAD

**Issue by kellington** [yeongbin-jo/python-chromedriver-autoinstaller#23]
Is there a way to direct auto installer to use Brace, not Chrome?

Message:
 No such file or directory: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

**Comment by yeongbin-jo** [comment]
Thanks for your post.

There are many chromium-based browsers in the world, and it is not easy to find the installed path for each of them.
Also, the method of checking the installed version cannot be guaranteed to be the same as the chrome browser.

For the reasons above, this library have supported and will support only for chrome and not chromium based browsers.
