### ISSUE TITLE
Windows Chrome check doesn't work if user doesn't launch Chrome

### ISSUE THREAD

**Issue by edbratt** [yeongbin-jo/python-chromedriver-autoinstaller#24]
Chrome apparently only updates the Registry entry when the user runs Chrome (maybe only in user mode). Therefore, when auto-update is applied and this is only run on headless versions of Chrome, the registry entry isn't updated. This prevents the update from being downloaded unless the user actually runs Chrome -- after this happens, the registry entry is updated and everything works as anticipated. This impacts 'lights-out' systems without much user activity.

Alternate version check that seems to work for me is:
`chromeVersion=subprocess.run(['chromedriver.exe', '--v'], stdout=subprocess.PIPE)`

**Comment by yeongbin-jo** [comment]
Thank you for post!

Reflecting your feedback, I will add a method to get the chrome version in the Windows environment in the next version.

**Comment by yeongbin-jo** [comment]
You can install chromedriver to any location you want via `path` option.
