### ISSUE TITLE
0.3.0 `install` signature incompatible with 0.2.2:  `cwd` is gone, `path` is new.

### ISSUE THREAD

**Issue by grantquail-BO** [yeongbin-jo/python-chromedriver-autoinstaller#26]
0.2.2 had the signature: `install(cwd: bool = False)`

and now the signature is: `install(path: str = None)`

This happened to break backwards compatibility, as we were calling with `install(cwd=True)`, and cwd became an invalid named argument..   

I'm posting this mostly so if people are in the same situation as me, you realize you're not crazy- you actually do have to change how you call that function.

Also, if you were calling install without naming the argument (i.e., `install(True)`) this will obviously not work as expected any more.

**Comment by yeongbin-jo** [comment]
Sorry, it's my mistake.
This issue will be resolved as soon as possible.

**Comment by yeongbin-jo** [comment]
@grantquail-BO I have released a new version that resolve this issue.
Please try again with version `0.3.1`.
Sorry for inconvenience.

**Comment by grantquail-BO** [comment]
> @grantquail-BO I have released a new version that resolve this issue. Please try again with version `0.3.1`. Sorry for inconvenience.

The code looks great, exactly what I was planning to submit myself!

This will make things a lot easier for a lot of people :D
