### ISSUE TITLE
Not compatible with python 3.5

### ISSUE THREAD

**Issue by anoop1409** [yeongbin-jo/python-chromedriver-autoinstaller#3]
File "/home/pi/.local/lib/python3.5/site-packages/chromedriver_autoinstaller/utils.py", line 185
    logging.debug(f'Downloading chromedriver ({chromedriver_version})...')
                                                                        ^
SyntaxError: invalid syntax

f string is not supported in python versions below 3.6.

**Comment by yeongbin-jo** [comment]
> File "/home/pi/.local/lib/python3.5/site-packages/chromedriver_autoinstaller/utils.py", line 185
> logging.debug(f'Downloading chromedriver ({chromedriver_version})...')
> ^
> SyntaxError: invalid syntax
> 
> f string is not supported in python versions below 3.6.

Thank you for reporting.

I am currently working on merging multiple webdriver autoinstallers into one library.
When that is done, you will be able to use more stable functions. Test automation will also be introduced at that time.

I apologize for any inconvenience.

**Comment by navdeepgaur** [comment]
@anoop1409 
I saw a workaround for getting the fstrings to work in older interpreters here: https://github.com/asottile/future-fstrings

You can try the following: 
`pip install future-fstrings[rewrite]`

and then do this right before you import fstring-laden modules in your script:

```python
import future_fstrings
future_fstrings.register()
```
worked on python 3.3 I tested,

Cheers!

**Comment by yeongbin-jo** [comment]
Due to the use of `fstrings` and `typehinting`,
it has been tentatively decided that this library only supports Python 3.6 and later.

Sorry for the late reply and not being able to help.
