### ISSUE TITLE
Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

### ISSUE THREAD

**Issue by JetReloader** [yeongbin-jo/python-chromedriver-autoinstaller#31]
I have almost none experience on coding I trying to learn rn how can fix this?
Idk which parts I need to show I think this will be enough

from bs4 import BeautifulSoup
import requests
import time

import selenium
import os
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

ser = Service("D:\chromedriver.exe")
driver = webdriver.Chrome(service=ser)

options = Options()
options.add_extension('D:\\xxxx.crx')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

with webdriver.Chrome(service=ser, options=options) as driver:
    doc_mw = BeautifulSoup(xxxx.text, "html.parser")
    print(doc.prettify())

**Comment by yeongbin-jo** [comment]
This issue is not related to the repository here.
