### ISSUE TITLE
Can you add the ability to specify the path for the driver to be stored

### ISSUE THREAD

**Issue by ladyageorge** [yeongbin-jo/python-chromedriver-autoinstaller#32]
I would like to be able to specify a location to store the driver as I have more then one test area and currently it seems to install it in the root of where I happen to be running from.. unless I am doing something wrong and perhaps someone could advise.  Thank you

**Comment by yeongbin-jo** [comment]
@ladyageorge 
You can achieve with this code

```python
import chromedriver_autoinstaller

chromedriver_autoinstaller.install(path="/path/to/you/want")
```

**Comment by ladyageorge** [comment]
When I try the path= I get an error...
chromedriver_autoinstall.install(path="/my/path")
E       TypeError: install() got an unexpected keyword argument 'path'

I am using package 0.0.7

any suggestions?

**Comment by yeongbin-jo** [comment]
@ladyageorge plz use latest (`0.4.0`) instead
