### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by michaelwmoreno** [yeongbin-jo/python-chromedriver-autoinstaller#38]
I'm getting a 403 Forbidden Error on this file.  http://doc.s3.amazonaws.com/2006-03-01 that it attempts to get a key from.  

Is there an alternative to this file that could be shared? 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>Z5AQQZH7JSNQ3X8Q</RequestId>
<HostId>RLmoFz9fEnwyWFC47wJA7ckr7VIxH1VcC3/lqN/PIuotvV3tRUx+vIL4oXjoj8W1/PawInNqkCY=</HostId>
</Error>

**Comment by yeongbin-jo** [comment]
As far as I know, that's the official distribution, so it's unlikely to change, and I'd recommend using a proxy if you're in an environment where access to that endpoint is difficult.
