### ISSUE TITLE
Installing 113 and saying it's 112

### ISSUE THREAD

**Issue by aestass** [yeongbin-jo/python-chromedriver-autoinstaller#40]
Hi! I'm using chromedriver_autoinstaller in a project. My browser's version is the latest 112 version. When I use autoinstaller, it creates a file "112" but then I get the following error when I run the code:

Message: unknown error: cannot connect to chrome at 127.0.0.1:61406\nfrom session not created: This version of ChromeDriver only supports Chrome version 113\nCurrent browser version is 112.0.5615.50\

Do you know how to get around this?

![image](https://user-images.githubusercontent.com/132581263/236218219-45594c68-54af-4a6c-a6f4-384ae25b1aad.png)

**Comment by DirkRichter** [comment]
- this is registry problem in windows: same as https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/issues/37
- fixed in pull request https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/pull/43

**Comment by yeongbin-jo** [comment]
제보 감사드립니다. PR #43 에 의해 해당 이슈는 수정 완료되었습니다.
