### ISSUE TITLE
For Windows Add Chrome Search Path for x86

### ISSUE THREAD

**Issue by lrowe8** [yeongbin-jo/python-chromedriver-autoinstaller#48]
Currently when looking for the version of Chrome in Windows, only the `Program Files` path is checked.  If Chrome was installed using an x86 installer the path should be `Program Files (x86)`.

**Comment by I-Margarini** [comment]
Having this same issue

**Comment by pasgeeken** [comment]
Me too, and going back to the previous version 0.4.0 worked

**Comment by yeongbin-jo** [comment]
Fixed in 0.6.1, thanks for reporting the issue.
