### ISSUE TITLE
Can't find path when making an executable

### ISSUE THREAD

**Issue by CheyenneH** [yeongbin-jo/python-chromedriver-autoinstaller#6]
When making an executable from code in which I have used this autoinstaller (extremely helpfull for other users of my program, so thank you for that!) I run into a problem that it cant find the path ('C:\\Users\\usr\\AppData\\Local\\Temp\\_MEI105922\\chromedriver_autoinstaller\\85'). Do you maybe have an idea why this is?

**Comment by michaelbukachi** [comment]
Which tool are you using to make the executable. Pyinstaller?

**Comment by CheyenneH** [comment]
Yes I'm using pyinstaller

**Comment by michaelbukachi** [comment]
Try adding it as a hiddenimport  e.g
`pyinstaller --hiddenimport chromedriver_autoinstaller ...py`

It has worked for me.

**Comment by brianyeap** [comment]
> Yes I'm using pyinstaller

did you manage to fix it? I am facing the same problem

**Comment by HuseyinAvci7** [comment]
> Try adding it as a hiddenimport e.g
> `pyinstaller --hiddenimport chromedriver_autoinstaller ...py`
> 
> It has worked for me.

this didn't work for me. but I solved it like this
`chromedriver_autoinstaller.install(True)`
doing so will create a folder for the downloaded driver.

**Comment by yeongbin-jo** [comment]
The cwd option (=current working directory) has been provided for operation in a distribution environment.
So the solution suggested by @HuseyinAvci7 is the correct one.

And from now on, it has been improved to explicitly specify the path to install chromedriver through the `path` parameter.
You may also consider using this option.
