### ISSUE TITLE
Wrong version extraction on Debian Linux

### ISSUE THREAD

**Issue by claudep** [yeongbin-jo/python-chromedriver-autoinstaller#62]
The install fails on my system because the returned version is `'116.0.5845.96 built on Debian 12.1, running on Debian 12.1'`, therefore no matches are done with the versions in `good_version_list["versions"]`. I suggest a regex to extract the version number, patch follows.

**Comment by Chetan11-dev** [comment]
yeongbin-jo hasn't fixed the issue even after 2 weeks. So, I created a fork named `chromedriver-autoinstaller-fix` to address this problem.

## Installation

```bash
pip install chromedriver-autoinstaller-fix
```

## Example

```python
from selenium import webdriver
import chromedriver_autoinstaller_fix

chromedriver_autoinstaller_fix.install()  
# Check if the current version of chromedriver exists
# and if it doesn't, download it automatically,
# then add chromedriver to path

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
```

## I would greatly appreciate a Star [here](https://github.com/omkarcloud/chromedriver-autoinstaller-fix) :)
