### ISSUE TITLE
Fallback version for no entry in google json

### ISSUE THREAD

**Issue by bopnrgi** [yeongbin-jo/python-chromedriver-autoinstaller#68]
Hi, 

The last version of Chrome on Ubuntu is Version 116.0.5845.110 (Official Build) (64-bit)

But, in googlechromelabs.github.io/chrome-for-testing/known-good-versions.json there is no entry for 116.0.5845.110.

Maybe it could be great to add a fallback to the last major version, or last working version ? 

Thanks

**Comment by Chetan11-dev** [comment]
yeongbin-jo hasn't fixed the issue even after 2 weeks. So, I created a fork named `chromedriver-autoinstaller-fix` to address this problem.

## Installation

```bash
pip install chromedriver-autoinstaller-fix
```

## Example

```python
from selenium import webdriver
import chromedriver_autoinstaller_fix

chromedriver_autoinstaller_fix.install()  
# Check if the current version of chromedriver exists
# and if it doesn't, download it automatically,
# then add chromedriver to path

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
```

## I would greatly appreciate a Star [here](https://github.com/omkarcloud/chromedriver-autoinstaller-fix) :)

**Comment by bopnrgi** [comment]
Thanks for your contribution and your fork.
After a long search, I use selenium python and now selenium provide a similar working solution as this repo to autodownload the right chrome driver executable.. (Called service). So I will no longueur this very useful package anymore...

**Comment by DennisBerboso** [comment]
Thanks for this! I was looking for a fix for a while now.

**Comment by DennisBerboso** [comment]
Thanks! This worked for me!

**Comment by yeongbin-jo** [comment]
Hi.
I would like to apologize to everyone who has used this package recently.
I haven't been using Selenium nowadays, so realized too late that this package was broken. 
To prevent this from happening again, I'm passing on maintainer privileges to anyone interested in this repository.

Again, I am very sorry for inconveniencing everyone, and thank you as always for your interest in this package.
