### ISSUE TITLE
linux/raspi

### ISSUE THREAD

**Issue by kyleok** [yeongbin-jo/python-chromedriver-autoinstaller#7]
thought it would work on raspberry pi since it's linux based, but didn't.

  File "/home/pi/.local/lib/python3.7/site-packages/chromedriver_autoinstaller/utils.py", line 53, in get_platform_architecture
    raise RuntimeError('Could not determine chromedriver download URL for this platform.')
RuntimeError: Could not determine chromedriver download URL for this platform.

any possibility for adding raspi compatibility?

**Comment by yeongbin-jo** [comment]
Sorry for the late reply.

May I know the return value of `sys.platform` and `sys.maxsize`?
