### ISSUE TITLE
Upload new version to PIP

### ISSUE THREAD

**Issue by smaxx1337** [yeongbin-jo/python-chromedriver-autoinstaller#73]
Hi!

2 weeks ago PR #72  has been merged but not pushed to PIP yet - is it possible to publish 0.6.4 with this bug fix?

**Comment by shawnCaza** [comment]
@yeongbin-jo Thanks for publishing the recent updates. 

I believe you might be the only one able to publish to pypi right now. If you're comfortable adding me as a collaborator on pypi I can help publish updates in the future.

**Comment by shawnCaza** [comment]
@smaxx1337 It looks like it did get published today.
