### ISSUE TITLE
no longer works with the latest chrome update 124

### ISSUE THREAD

**Issue by sonkite225** [yeongbin-jo/python-chromedriver-autoinstaller#74]
no longer works with the latest chrome update 124

can it be fixed please or anyone knows a workaround or something else?

**Comment by shawnCaza** [comment]
Can you provide more details on system,  exact version number, and error message?

I was able to run successfully for Chrome 124.0.6367.62 on MacOS x64

**Comment by sonkite225** [comment]
it was on Chrome 124.0.6367.61, but never mind, today it works again. maybe there was an dl problem of the driver from google itself yesterday. thx
