### ISSUE TITLE
Cannot find Chrome binary

### ISSUE THREAD

**Issue by rishiajmera** [yeongbin-jo/python-chromedriver-autoinstaller#8]
Hello,
I have been using this library for a long time now and it has been working perfectly fine until recently. It's a great help! Thank you.

I am getting the following error for past few days and have to keep chomedriver.exe file along with my program. If there is any solution, it would be a great help again.

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

I am using python3.6.8 and windows platform.

**Comment by yeongbin-jo** [comment]
chromedriver worked fine, but chromedriver doesn't seem to be able to find the location of chrome.
I think the snippet below will help you.

```python
from selenium.webdriver.chrome.options import Options

options = Options()
options.binary_location= 'C:/Program Files/Google/Chrome/Application/chrome.exe'
driver = webdriver.Chrome(chrome_options=options)
```
